version: '3.4'

services:
  toolsfactory.home.adapters.multihost:
    image: ${DOCKER_REGISTRY-}toolsfactoryhomeadaptersmultihost
    build:
      context: .
      dockerfile: src/Toolsfactory.Home.Adapters.MultiHost/Dockerfile
